# -*- coding: utf-8 -*-
{
    'name':"ShowTime",
    'depends':['base','contacts'],
    'license':"LGPL-3",
    'data':[
        'security/ir.model.access.csv',
        'views/res_partner_views.xml',
        'views/showtime_ticket_order_views.xml',
        'views/showtime_tickets_views.xml',
        'views/showtime_venue_tag_views.xml',
        'views/showtime_shows_views.xml',
        'views/showtime_sections_views.xml',
        'views/showtime_venue_views.xml',
        'views/showtime_venue_type_views.xml',
        'views/showtime_menus.xml',
        'data/showtime_data.xml',
        'data/cron_data.xml',
    ],
    'demo':[
        'data/demo_data.xml',
    ],
    'application':True,
}
